### ISSUE TITLE
Failure during startup - ASCOM.devicehub.Dome is not registered as a device of type:Dome

### ISSUE THREAD

**Issue by mdolenga** [ASCOMInitiative/ASCOMDeviceHub#10]
Latest build 6.4.1.11 on Windows 10 with all updates.

I have successfully used this app for several months to manage my 32 bit focuser driver (FLI ASCOM) so that I can use it with 64 bit NINA. Last night, it worked without issue. 

This evening it fails with the error message in the title of this issue. I made no changes to my device during that time. I have no dome, nor do I use device hub to connect to my telescope driver.

Is there some way to disable loading the dome at startup perhaps? I have uninstalled and reinstalled the application to no avail. 

I see the error in a message box when I tried reinstalling - on a normal launch, there is no way to get to the application window.

**Comment by Peter-Simpson** [comment]
Hi,

 

We use this list mostly for issues in the Platform and, from your description, it doesn’t sound like you have an issue with the Platform itself. Personally, I don’t think the Platform maintainers have experience of FLI cameras or NINA so you may get a better response by posting on the FLI  or NINA support sites or on the ASCOM Talk site here: https://ascomtalk.groups.io/g/Help/topics 

 

Best wishes, Peter

**Comment by astroman133** [comment]
It is by design that DeviceHub registers all three device types at startup.

The error you are reporting is most likely due to a corrupted Windows Registry. The only solution that comes to mind is to unregister and re-register the device hub application To do this open a command prompt window and change the command prompt's current directory to the directory containing the DeviceHub executable. Then type the following two lines

ASCOM.DeviceHub.exe /unregister
ASCOM.DeviceHub.exe /register

As an alternative you could un-install DeviceHub and re-install it.

Either option should repair the registry entries that are used by DeviceHub.
