### ISSUE TITLE
Error in ASCOM Device Hub User and Technical Information Guide

### ISSUE THREAD

**Issue by kmorris1077** [ASCOMInitiative/ASCOMDeviceHub#12]
Under the "Device Configuration" section of the Technical Information Guide, there is this sentence "In the example on the right, point A is 9 mm east of the dome origin, 48 mm north of the dome origin and 44 mm above the dome origin."

The referenced example diagram is missing and adding it would be a boon for those of us trying to get our dome geometry settings correct.

**Comment by astroman133** [comment]
The example that is referenced in the User Guide is the screenshot to the immediate right of the text that shows the Dome Setup panel. I did update the screenshot so that the displayed values match the narrative.

I did not include a diagram of how to measure coordinate offsets in 3-dimensional space. The only examples of diagrams that I saw were not clear enough and were as likely to cause confusion as they were to remedy it.

The updated document is included in version 6.5.1.2.

Thanks!
