### ISSUE TITLE
Feature Request for Dome Slaving extension

### ISSUE THREAD

**Issue by robertpascale** [ASCOMInitiative/ASCOMDeviceHub#6]
Currently, I have a lot of problems with software that either does not have dome control, or has poor dome control (eg. dome pointing isn't working well).
However, I have no problems with ASCOM Device Hub pointing - it works perfectly well - no alignment issues and very stable.

However, as part of the automation of my imaging software, I'd like to be able to ensure I can close the dome when the imaging software is done.

My idea here is that the device hub can extend the concept of the "slave dome" to include the ability to park the dome when the telescope is parked.

ie. Park Telescope = Park Dome when slaving is enabled.

Conversely, you could have another option, when a scope is UNPARKED, this will UNPARK the dome, open the shutter and start slaving the dome.

This effectively makes the dome completely automatable from the perspective of a "dumb" imaging software solution.

**Comment by astroman133** [comment]
You may be oversimplifying the situation.  First, Device Hub is not intended to be an observatory control system. Observatory control would use additional sensors to verify that the telescope is actually in a safe position before closing the dome, rather than simply relying on the telescope to say that it is parked. This is especially important if the dome is not a dome, but a roll-off roof.

Certainly, it would be not terribly difficult to write a client application that could do what you want, or purchase a commercial observatory control application.

**Comment by robertpascale** [comment]
Didn't think of some of the other aspects of this.
The request comes as a result of other programs not doing their jobs properly, and Device Hub doing a great job of actually controlling the dome with the scope, it seemed like a small leap to extend the functionality. I understand though that it does diverge a little from purely being a device hub however.
In my mind though, the open/close/park functions and the safety considerations are no different than the scope turning, nor indeed if I were to push the "close" button or "park" button in device hub, however, I do understand your position.

**Comment by Rojoyinc** [comment]
Robert - my cloudwatcher will execute a script when it flags unsafe (cloud/rain/etc). 
At the end of a session it runs the script. The script custom parks the RASA face down weights up (due to no dust cap) then the script home's the dome and closes the shutter.  This might be helpful to you.    My only problem is - when a sequence in NINA ends the dome won't close until (unsafe in the cloudwatcher) if it's never unsafe, it can sit open for hours until dawn is detected and then it closes. (worst case scenerio).   I had pushed for NINA to add a script at the end of a sequence to shut the dome.

**Comment by astroman133** [comment]
This request is outside of the scope for Device Hub. I am marking it as closed.
