### ISSUE TITLE
log commands to file

### ISSUE THREAD

**Issue by nevion** [ASCOMInitiative/ASCOMDeviceHub#7]
something like a json log of commands executed would be great - a live filter of some kind , like device type (main interest to me right now is just telescope) and method (main interest to me now is pulseguide) would be great.

**Comment by astroman133** [comment]
DeviceHub has an activity log that displays a logged messages to a dialog window. At any time you can copy the contents of the window to the Windows Clipboard and paste them into a text editor like Notepad to save to a text file. This is by design. You can select the messages to display by device and message class.
